name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Adjust version number
        shell: bash
        env:
          CUR_VERSION: ${{ github.event.release.tag_name }}
          TARGET: ${{ github.workspace }}/src/proflame_wifi/__init__.py
        run: sed -ri "s/__version__\s*=\s[\"'][^\"']+[\"']/__version__ = '${CUR_VERSION#v}'/" "${TARGET}"
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --repository pypi dist/*
